package-lock.json
package.json
src/App.jsx
src/components/Navbar.css
src/components/Navbar.jsx
src/components/Slider.jsx
src/components/UserMenu.module.css
src/index.css
src/pages/Calender.jsx
src/pages/Home.jsx
src/pages/Magazine.jsx

feat : Navbar&Carousel

---

src/App.jsx
src/components/MainSlider.jsx
src/components/SubSlider.jsx
src/pages/Home.jsx
src/pages/Home.module.css
src/pages/Survey.jsx

feat: update Carousel & add Survey

feat: update Carousel & add Survey

---

src/App.jsx
src/components/Navbar.jsx
src/components/UserMenu.jsx
src/functions/useSignupToken.js
src/pages/Register_success.jsx
src/pages/login.jsx
src/pages/register.jsx

feat: 회원가입,로그인/로그아웃,유효성 기능 추가

---

package-lock.json
package.json
src/App.jsx
src/components/Navbar.css
src/components/Navbar.jsx
src/components/UserMenu.module.css
src/index.css
src/pages/About.jsx
src/pages/Calender.jsx
src/pages/Home.jsx
src/pages/Magazine.jsx
src/pages/NotFound.jsx
src/pages/Register_success.jsx

- 네비게이션바 크기를 전체 화면 사이즈로 수정.
- 네비게이션바 정렬 및 css 수정.
- 데스크탑 기본 뷰 사이즈 1224에서 1424로 변경.

style: 네비게이션 바 및 데스크탑 뷰 크기 조정 등. 

---

package-lock.json
package.json
src/components/Navbar.css
src/components/Navbar.jsx
src/pages/Home.jsx
src/pages/Home.module.css
src/pages/login.jsx
src/pages/register.jsx

feat: UI update

---

src/App.jsx
src/components/MainSlider.jsx
src/pages/Home.jsx

feat: Homepage Update

---

src/App.jsx
src/components/SurveyForm.jsx
src/pages/Survey.jsx

feat:Survey 

---

src/App.jsx

fix:Survey APP 수정

---

package-lock.json
package.json

package.json
package-lock.json
두 파일 dependencies에 FullCalendar 관련 패키지 등록 안되있는거 확인했고 고쳤음.

fix:package.json (FullCalendar패키지 관련)

---

src/components/Functions/ProtectedRoute.js
src/components/Functions/PublicRoute.js
src/components/Navbars/ExamplesNavbar.js
src/components/Navbars/IndexNavbar.js
src/index.js
src/views/examples/CalendarPage.js
src/views/examples/LandingPage.js
src/views/examples/LoginPage.js
src/views/examples/ProfilePage.js
src/views/examples/RegisterPage.js

로그아웃 버튼 추가하고 로그인 전후로 navbar 변경되게 바꿈

feat:login/logout navbar UI

---

src/views/examples/FileUploaderPage.js

feat: navbar fix

---

src/views/examples/ResultPage.js

feat: navbar fix2

---

src/components/Navbars/IndexNavbar.js
src/views/Index.js
src/views/examples/HaircareProductPage.jsx
src/views/examples/SurveyPage.jsx

feat: navbar update

---

src/components/Headers/IndexHeader.js
src/components/Navbars/IndexNavbar.js
src/index.js
src/views/Index.js
src/views/examples/FileUploaderPage.js
src/views/examples/HaircareProductPage.jsx
src/views/examples/MagazinePage.js
src/views/examples/ResultPage.js
src/views/examples/SurveyPage.jsx
src/views/index-sections/CarouselM1.js
src/views/index-sections/CarouselM2.js
src/views/index-sections/Introduction.js
src/views/index-sections/Tabs.js

feat: UI overall update

---

src/components/Functions/AuthContext.js

feat: login Cookie add

---

src/views/Index.js
src/views/examples/MagazinePage.js
src/views/index-sections/CarouselM1.js
src/views/index-sections/CarouselM2.js
src/views/index-sections/CompleteExamples.js
src/views/index-sections/Introduction.js
src/views/index-sections/Tabs.js

- CompleteExamples, Introduction, CarouselM1, Tabs, CarouselM2 스타일 변경: 글자 및 각종 스타일 변경. 
- 매거진 페이지 내 사진 변경.

style: 홈 페이지 스타일 변경

---

src/views/examples/MagazinePage.js

feat: magazine update

---

src/views/examples/MagazinePage.js

feat: magazine image fix

---

src/views/examples/FileUploaderPage.jsx
src/views/index-sections/CarouselM2.js
src/views/index-sections/ResultChart.jsx
src/views/index-sections/SurveyForm.jsx
src/views/index-sections/Tabs.js

- 홈페이지: tab, 캐러셀2 모바일 뷰 수정. 
- 파일 업로드 페이지: fontweight 수정. 
- resultchart: 차트 크기 조정.

style: 홈 페이지 모바일 뷰 수정 및 타 페이지 글자 크기 조정.

---

src/views/examples/RegisterPage.jsx

중복확인 버튼을 만들고, 중복확인 해야지 회원가입 진행하도록 변경.
중복확인 후 nickname 필드값이 변하면 중복확인 초기화.

Feat: ID duplication check

---

package-lock.json
package.json
src/components/Headers/IndexHeader.js
src/components/Headers/MobileIndexHeader.js
src/views/Index.js

수정내용요약
1. 모바일뷰, 데스크탑뷰에서 메인페이지 상단 헤더부분의 "지금바로 시작하기" 링크의 가독성 향상
2. 기타 경미한 버그 수정

2023.12.15 (2)

---

src/components/Headers/IndexHeader.js
src/components/Headers/MobileIndexHeader.js

FIX:메인페이지 버그 수정

---

src/components/Headers/IndexHeader.js
src/components/Headers/MobileIndexHeader.js

FIX:오탈자 수정

---

src/views/examples/RegisterPage.jsx
src/views/examples/ResultPage.jsx

Fix: pw check 수정

---

src/components/Headers/MobileIndexHeader.js

style: 모바일 인덱스 헤더 글씨 정렬 수정
